### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by homdx** [shashi278/Kivy-random-desktop-app#1]
AttributeError: 'NoneType' object has no attribute 'cursor'

Errror: unable to open database file
 Traceback (most recent call last):
   File "main.py", line 483, in <module>
     Diary().run()
   File "venv3/lib/python3.6/site-packages/kivy/app.py", line 825, in run
     self.dispatch('on_start')
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "main.py", line 460, in on_start
     c= conn.cursor()
 AttributeError: 'NoneType' object has no attribute 'cursor'

**Comment by shashi278** [comment]
> AttributeError: 'NoneType' object has no attribute 'cursor'
> 
> Errror: unable to open database file
> Traceback (most recent call last):
> File "main.py", line 483, in 
> Diary().run()
> File "venv3/lib/python3.6/site-packages/kivy/app.py", line 825, in run
> self.dispatch('on_start')
> File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
> File "main.py", line 460, in on_start
> c= conn.cursor()
> AttributeError: 'NoneType' object has no attribute 'cursor'

Thank you for raising the issue.
Actually, on my computer I already had a folder named "database" in which I'd create .db files and later would connect to them.
So, on any other system the "connect_database" function can't find, for example, the "database/db_612019.db" and so it'd return a None to "conn" and hence the AttributeError: 'NoneType' object has no attribute 'cursor'.
The code has been updated such that if there's no such file called "database", it'll create one. Also, I've added some conditionals to check for "conn" is not None.

**Comment by shashi278** [comment]
This issue has been fixed so I'm closing this thread.
